### ISSUE TITLE
Issue when importing?

### ISSUE THREAD

**Issue by Javi3rV** [cgtinker/blendartrack#14]
I'm not sure if this problem is because I'm new, but when I import I have 3 problems (not BIG problems, they have easy fix manually)

- Reference objects are not adjusted to the floor (I mean 0 at Z axis)
- I chose 1920x1080 30fps in the app, but the addon sets a 2400x1080 camera

I always have to fix them, but it may be possible to do it automatically.

To reproduce it, I just record with the app and this settings ON:
- general: 1st and 2nd 
- camera tracknig: 1st 
- point cloud density: default (5)
- resolution: 1920x1080 30fps
- max bitrate

Then, import with addon.

**Comment by cgtinker** [comment]
Hey there,

actually, that's how the app functions and not a bug. It may seems slightly inconvenient in your case but there are reasons to it:

1. There's a recorded resolution and a screen resolution, to mimic the detection results 1-1, the devices screen resolution gets set as blenders scene resolution. In some cases, changing the resolution as you have done, can lead to floating objects - your devices resolution is pretty close to the recorded resolution so it works and might seem like a bug :)
2. The origin (0, 0, 0) of the scene is the initial camera position. This does not mean you should start recording at the ground, it's just the entry point. That's why markers are usually below zero.
